FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["Quorom.csproj", "./"]
RUN dotnet restore "./Quorom.csproj"
COPY . .
RUN dotnet build "Quorom.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Quorom.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Quorom.dll"]
